version: 0.2
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run testci -- --CI --passWithNoTests
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: "build"
